[package]
name = "ai_sh"
version = "0.1.0"
edition = "2021"

[dependencies]
"dotenv"="*"
"regex"="*"
"openai-api-stream-rs" = "0.1.0"
"tokio" = { version = "1.12.0", features = ["full"] }
"futures" = "0.3.19"
tinytemplate = "1.2.1"

[[bin]]
name = "ai"
path = "./src/main.rs"